-- Databricks notebook source
-- MAGIC %md
-- MAGIC ### Example Exploratory Notebook
-- MAGIC
-- MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
-- MAGIC
-- MAGIC **Note**: This notebook is not executed as part of the pipeline.

-- COMMAND ----------

USE CATALOG `workspace`;
USE SCHEMA `default`;

-- COMMAND ----------

-- Installing Python packages such as Polars is not supported in SQL cells.
-- Use %pip install polars in a Python cell to install the package.
